name: "Build"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          architecture: x64
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
      - name: Build with Maven
        run: mvn --no-transfer-progress package -DskipTests
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3